apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "podchaosmonkey.fullname" . }}
  namespace: {{ .Values.targetNamespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]