apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "podchaosmonkey.fullname" . }}
  namespace: {{ .Values.targetNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "podchaosmonkey.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "podchaosmonkey.fullname" . }}
  apiGroup: rbac.authorization.k8s.io